### ISSUE TITLE
Update existing reviews with more metadata

### ISSUE THREAD

**Issue by seadubs** [winesbyjeremy/winesbyjeremy.com#53]
Tagging @worldlysage to update the rest of the existing reviews with additional metadata. Feel free to go ahead and do it on this branch: https://github.com/winesbyjeremy/winesbyjeremy.com/tree/feature-content/more_review_metadata

Once complete, that branch already contains the updated review.html necessary to include that metadata.

**Comment by worldlysage** [comment]
Completed, merged to master, and deleted the branch.  Thanks @seadubs
